const supabaseUrl = "https://kkrbmuwwaxejfdqiczee.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcmJtdXd3YXhlamZkcWljemVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0ODc4MjYsImV4cCI6MjA3ODA2MzgyNn0.YtBWvo2DA9x49dN5C14jHRxWD4Hes7tOMnxMAdED86A";
const supabase = window.supabase.createClient(supabaseUrl, supabaseKey);